apiVersion: v1
kind: Service
metadata:
  name: {{ include "finalproject.fullname" . }}
  labels:
    app: finalproject
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "finalproject.selectorLabels" . | nindent 4 }}
